//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaConquista_WF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHistoricoMovimientoInventario
    {
        public int hmovinv_Id { get; set; }
        public int tminv_Id { get; set; }
        public int invp_Id { get; set; }
        public int hmovinv_qtity { get; set; }
        public int hmovinv_Stock { get; set; }
        public Nullable<bool> hmovinv_Estado { get; set; }
        public int UsuarioCrea { get; set; }
        public System.DateTime FechaCrea { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual tbInventarioProductos tbInventarioProductos { get; set; }
        public virtual tipoMovimientoInventario tipoMovimientoInventario { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
    }
}
