//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaConquista_WF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoMovimientoInventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipoMovimientoInventario()
        {
            this.tbHistoricoMovimientoInventario = new HashSet<tbHistoricoMovimientoInventario>();
        }
    
        public int tminv_Id { get; set; }
        public string tminv_Descripcion { get; set; }
        public Nullable<bool> tminv_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHistoricoMovimientoInventario> tbHistoricoMovimientoInventario { get; set; }
    }
}
